/**
 * Broker.ManagementApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateServerBalanceRequest { 
    serverId?: number;
    freeUserCount?: number | null;
    priceByUser?: number | null;
    balance?: number | null;
    reason?: string | null;
    totalUserCount?: number | null;
}

